export interface OrderList {
    merchantName?:string;
    transactionId?: number;
    omsOrderRefNumber?: string;
    storeOrderRefNumber?: string;
    createDateTime?: string;
    transactionDateTime?: string;
    branchName?: string;
    branchId?: number;
    deliveryCompanyId?: number;
    deliveryCompanyName?: string;
    customerName?: string;
    customerPhone?: string;
    deliveryCityId?: number;
    deliveryCity?: string;
    deliveryAddress?: string;
    paymentModeId?: number;
    paymentMode?: string;
    trackingNumber?: string;
    invoicePayment?: number;
    isSplit?: boolean;
    orderWeight?: string;
    transactionStatusId?: number;
    transactionStatus?: string;
    shipmentTypeId?: number;
    shipmentType?: string;
    deliveryTypeId?: number;
    deliveryType?: string;
    pickupAddress?: string;
    pickupCityId?: number;
    pickupCity?: string;
    customerAddress?: string;
    transactionProducts?: (TransactionProduct)[];
    orderTax?: number;
    shippingCharges?: number;
    discountType?: string;
    discountAmount?: number;
    deliveryCharges?: number;
    transactionType?: number;
    transactionReturnId?: number;
    transactionReturnReason?: string;
    returnDescription?: string;
    transactionReversalAttachments?: any[];
    apartmentNo?: string;
    streetNo?: string;
    transactionSubStatus?: string;
    warehouseStatus?: string;
    [key: string]: any;
  }
  export interface TransactionProduct {
    transactionProductId?: number;
    productId?: number;
    productName?: string;
    skuNumber?: string;
    productDescription?: string;
    productUnitPrice?: string;
    productTax?: string;
    productWeight?: string;
    productCategoryId?: number;
    productCategory?: string;
    productQuantity?: number;
  }